# Web Scraping com Selenium
Nesta aula iremos criar uma **automação na internet** utilizando a biblioteca Selenium

#### Passo 1: Instalar biblioteca

In [2]:
# Remova o comentário(#) da linha abaixo caso esteja executando este script pela primeira vez
#%pip install --upgrade selenium
#%pip install webdriver-manager

Collecting selenium
  Downloading selenium-4.47.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: certifi>=2026.2.25 in c:\Users\47806295860\AppData\Local\Programs\Python\Python314\Lib\site-packages (from selenium) (2026.7.22)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.34.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in C:\Users\47806295860\AppData\Roaming\Python\Python314\site-packages (from selenium) (4.16.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\Users\47806295860\AppData\Local\Programs\Python\Python314\Lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Collecting websocket-client<2.0,>=1.8.0 (from selenium)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting attrs>=23.2.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in c:\Users\47806295860\AppData\Local\Programs\Python\Python314\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.19)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting cffi>=1.14 (from trio<1.0,>=0.31.0->selenium)
  Downloading cffi-2.1.1-cp314-cp314-win_amd64.whl.metadata (2.6 kB)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting pycparser (from cffi>=1.14->trio<1.0,>=0.31.0->selenium)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting h11<1,>=0.16.0 (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading selenium-4.47.0-py3-none-any.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.5 MB 8.8 MB/s eta 0:00:01
   -------------- ------------------------- 3.4/9.5 MB 10.8 MB/s eta 0:00:01
   ------------------------ --------------- 5.8/9.5 MB 10.6 MB/s eta 0:00:01
   ---------------------------------- ----- 8.1/9.5 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 9.7 MB/s  0:00:01
Downloading trio-0.34.0-py3-none-any.whl (511 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Downloading websocket_client-1.9.0-py3-none-any.whl (82 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading cffi-2.1.1-cp314-cp314-win_amd64.whl (187 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, websocket-client, sniffio, pysocks, pycparser, h11, attrs, wsproto, outcome, cffi, trio, trio-websocket, selenium

   ----------------------------------------  0/13 [sortedcontainers]
   --- ------------------------------------  1/13 [websocket-client]
   --- ------------------------------------  1/13 [websocket-client]
   --- ------------------------------------  1/13 [websocket-client]
   --- ------------------------------------  1/13 [websocket-client]
   --- ------------------------------------  1/13 [websocket-client]
   --- ------------------------------------  1/13 [websocket-client]
   --- ------------------------------------  1/13 [websocket-client]
   --- ------------------------------------  1/13 [websocket-client]
   ------ ---------------------------------  2/13 [sniffio]
   ------ ---------------------------------  2/13 [sniffio]
   --------- ------------------------------  3/13 [pysocks]
   ------------ ---------------------------  4/13 [pycparser]
   ------------ ---------------------------  4/13 [pycparser]
   --------------- ------------------------  5/13 [h11]
   --------------- ------------------------  5/13 [h11]
   --------------- ------------------------  5/13 [h11]
   ------------------ ---------------------  6/13 [attrs]
   ------------------ ---------------------  6/13 [attrs]
   ------------------ ---------------------  6/13 [attrs]
   ------------------ ---------------------  6/13 [attrs]
   ------------------ ---------------------  6/13 [attrs]
   --------------------- ------------------  7/13 [wsproto]
   --------------------- ------------------  7/13 [wsproto]
   ------------------------ ---------------  8/13 [outcome]
   --------------------------- ------------  9/13 [cffi]
   --------------------------- ------------  9/13 [cffi]
   --------------------------- ------------  9/13 [cffi]
   --------------------------- ------------  9/13 [cffi]
   --------------------------- ------------  9/13 [cffi]
   --------------------------- ------------  9/13 [cffi]
   --------------------------- ------------  9/13 [cffi]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   --------------------------------- ------ 11/13 [trio-websocket]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ---------------------------------------- 13/13 [selenium]

Successfully installed attrs-26.1.0 cffi-2.1.1 h11-0.16.0 outcome-1.3.0.post0 pycparser-3.0 pysocks-1.7.1 selenium-4.47.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.34.0 trio-websocket-0.12.2 websocket-client-1.9.0 wsproto-1.3.2

#### Passo 2: Importar bibliotecas

In [3]:
import pandas as pd

# Módulo que fornece a classe principal para criar e controlar instâncias do navegador
from selenium import webdriver 

# Módulo para localização de elementos na página
from selenium.webdriver.common.by import By

# Módulo para simular as teclas
from selenium.webdriver.common.keys import Keys

#### Passo 3: Criar navegador

In [4]:
driver = webdriver.Chrome()  # Cria uma instância do navegador Chrome

#### Passo 4: Acessar site

In [5]:
# url: 'https://pubmed.ncbi.nlm.nih.gov/

driver.get('https://pubmed.ncbi.nlm.nih.gov/')  # Abre a página do PubMed

#### Passo 5: Fechar navegador

In [6]:
driver.quit()

#### Passo 6: Acessar site e obter elementos elementos html

Para obter os elementos do site existem basicamente dois comandos
- find_element() -> Para acessar apenas um elemento
- find_elements() -> Para acessar vários elementos de uma vez

A partir destes comandos podemos usar vários métodos de seleção, por:
- **tag_name:** Localiza elementos com nome de tag correspondente ao valor de pesquisa
- **id:** Localiza elementos com atributo ID correspondente ao valor de pesquisa
- **class_name:** Localiza elementos com nome de classe que contém o valor de pesquisa (nomes de classe compostos não são permitidos)
- **css_selector:** Localiza elementos que correspondem a um seletor CSS
- **name:** Localiza elementos com atributo NAME correspondente ao valor de pesquisa
- **xpath:** Localiza elementos que correspondem a uma empressão XPath
- **link_text:** Localiza elementos âncora em que o texto visível corresponde ao valor de pesquisa
- **partial link text:** Localiza elementos âncora em que o texto visível contém o valor de pesquisa. Se vários elementos forem correspondentes, apenas o primeiro será selecionado

Após selecionar os elementos podemos executar algumas ações:
- **click():** Simula um clique do mouse em um elemento. Exemplo: elemento.click().
- **send_keys('Text'):** Insira texto em um campo. Exemplo: elemento.send_keys("texto a ser inserido").
- **clear():** Remova o texto existente em um campo de texto. Exemplo: elemento.clear().
- **submit():** Envie um formulário. Exemplo: elemento.submit().
- **select_by_visible_text('Texto'):** Selecione uma opção em uma lista suspensa por texto visível. Exemplo: elemento.select_by_visible_text("Opção Desejada").
- **Keys.ENTER:** Simula a tecla Enter. Pode ser usado em combinação com send_keys()para enviar formulários ou em outras situações que desative a tecla Enter. Exemplo: elemento.send_keys(Keys.ENTER).

#### 6.1: Criar navegador e acessar site

In [7]:
driver = webdriver.Chrome()  # Cria uma instância do navegador Chrome
driver.get('https://pubmed.ncbi.nlm.nih.gov/')  # Abre a página do PubMed

#### 6.2: Selecionar o campo de busca pelo id

In [8]:
campo_busca = driver.find_element(By.ID, 'id_term')  # Localiza o campo de busca pelo ID

#### 6.3: Escrever um texto no campo de busca

In [10]:
campo_busca.send_keys('Pokemon')

#### 6.4: Clicar no Botão Pesquisar

In [16]:
driver.find_element(By.CLASS_NAME,'search-btn').click()  # Localiza o botão de busca pelo nome da classe e clica nele

#### 6.5: Fechar navegador

In [17]:
driver.quit()

#### Passo 7: Obter elementos dos resultados de busca

In [37]:
driver = webdriver.Chrome()  # Cria uma instância do navegador Chrome
driver.get('https://pubmed.ncbi.nlm.nih.gov/')  # Abre a página do PubMed
campo_busca = driver.find_element(By.ID, 'id_term')  # Localiza o campo de busca pelo ID
campo_busca.send_keys('Pokemon', Keys.ENTER)  # Digita "Pokemon" no campo de busca e pressiona Enter
resultado = driver.find_elements(By.CLASS_NAME, 'docsum-content')  # Localiza o elemento que contém os resultados da busca
print("total de resultados: ", len(resultado))  # Imprime o texto do elemento que contém os resultados da busca

total de resultados:  10

#### 7.1: Listar o título de todos os resultados

In [38]:
lista_de_titulos = []

for i in resultado:
    lista_de_titulos.append(i.find_element(By.CLASS_NAME, 'docsum-title').text)  # Adiciona o texto do elemento que contém os resultados da busca à lista de títulos
lista_de_titulos

['Primary Care: Its Pokemon Moment.',
 'Impact of Pokemon Go on Physical Activity: A Systematic Review and Meta-Analysis.',
 'Effects of Pokemon GO on Physical Activity and Psychological and Social Outcomes: A Systematic Review.',
 'Influence of Pokemon GO on Physical Activity and Psychosocial Well-Being in Children and Adolescents: Systematic Review.',
 'Going Forward with Pokemon Go.',
 'Pokemon contagion.',
 'Random forests, sound symbolism and Pokemon evolution.',
 'Pokemon Go and augmented virtual reality games: a cautionary commentary for parents and pediatricians.',
 'Pokemon inhibits Bim transcription to promote the proliferation, anti-anoikis, invasion, histological grade, and dukes stage of colorectal neoplasms.',
 'Pokemon GO and Physical Activity in Asia: Multilevel Study.']

#### 7.2: Listar o link de todos os resultados

In [50]:
lista_de_links = []

for j in resultado:
    lista_de_links.append(j.find_element(By.CLASS_NAME, 'docsum-title').get_attribute('href'))
lista_de_links

StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=151.0.7922.174); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff7e913abb5+151b5]
	chromedriver!GetHandleVerifier [0x7ff7e913ac10+15210]
	chromedriver!(No symbol) [0x7ff7e8c65d6d]
	chromedriver!(No symbol) [0x7ff7e8c7da3e]
	chromedriver!(No symbol) [0x7ff7e8c7c140]
	chromedriver!(No symbol) [0x7ff7e8c6e93d]
	chromedriver!(No symbol) [0x7ff7e8c6c72e]
	chromedriver!(No symbol) [0x7ff7e8c70c85]
	chromedriver!(No symbol) [0x7ff7e8c70d4f]
	chromedriver!(No symbol) [0x7ff7e8cc0a0a]
	chromedriver!(No symbol) [0x7ff7e8cc158c]
	chromedriver!(No symbol) [0x7ff7e8cb50cc]
	chromedriver!(No symbol) [0x7ff7e8cb4f76]
	chromedriver!(No symbol) [0x7ff7e8d0ec0b]
	chromedriver!(No symbol) [0x7ff7e8cb37cc]
	chromedriver!(No symbol) [0x7ff7e8cb46f3]
	chromedriver!GetHandleVerifier [0x7ff7e975b79b+635d9b]
	chromedriver!GetHandleVerifier [0x7ff7e9755ac6+6300c6]
	chromedriver!GetHandleVerifier [0x7ff7e977bcee+6562ee]
	chromedriver!GetHandleVerifier [0x7ff7e9158ffe+335fe]
	chromedriver!GetHandleVerifier [0x7ff7e916147c+3ba7c]
	chromedriver!GetHandleVerifier [0x7ff7e9144d64+1f364]
	chromedriver!GetHandleVerifier [0x7ff7e9144ef4+1f4f4]
	chromedriver!GetHandleVerifier [0x7ff7e9127d97+2397]
	KERNEL32!BaseThreadInitThunk [0x7ff93f7cccb7+17]
	ntdll!RtlUserThreadStart [0x7ff940dcad6c+2c]

#### 7.3: Acessar um dos links

In [ ]:
driver.get(lista_de_links[0])

## Exercício 1
Acesse um dos links da lista e obtenha:

##### 1) Título

In [ ]:
titulo = driver.find_element(By.CLASS_NAME, 'heading-title').text
print(titulo)

Primary Care: Its Pokemon Moment

##### 2) Autores

In [ ]:
autor = driver.find_element(By.CLASS_NAME, 'full-name').text
print(autor)

Bryan Becker

##### 3) Ano de publicação

In [51]:
ano_publicacao = driver.find_element(By.CLASS_NAME, 'secondary-date').text
print(ano_publicacao)

Epub 2024 Mar 29.

##### 4) DOI

In [53]:
DOI = driver.find_element(By.CLASS_NAME, 'identifier.doi').text
print(DOI)

DOI: 10.1016/j.amjmed.2024.03.020

##### 5) Tipo de publicação

In [54]:
tipo_publicacao = driver.find_element(By.CLASS_NAME, 'publication-type').text
print(tipo_publicacao)

Review

##### 6) Resumo

In [55]:
resumo = driver.find_element(By.CLASS_NAME, 'abstract-content.selected').text
print(resumo)

Primary care in the United States is undergoing bursts of evolution in response to health system stresses, changing demographics, and expansion of risk and value-based reimbursement structures. The impact of primary care remains substantive and associated with improved population health. However, the spectrum of services, the nature of the physicians involved and new ways of including the patient in her, or his own care suggests that a new definition of primary care be considered, and patient expectations be heeded and understood. Evolutionary bursts yield new traits and in primary care, they are spawning new care models with significant implications for general internal medicine, internal medicine/pediatrics trained individuals and medicine subspecialties given the focus of these models on Medicare Advantage. Ultimately, changes in reimbursement and creative incentives will be two factors among many that will solidify the next stage of primary care in the United States.

##### 7) Link de acesso (como registro de referência)

In [57]:
link_deacesso = driver.find_element(By.CLASS_NAME, 'link-item').get_attribute('href')
print(link_deacesso)

https://linkinghub.elsevier.com/retrieve/pii/S0002-9343(24)00166-9

In [59]:
dados = {
    'titulo': titulo,
    'autor': autor,
    'ano_publicacao': ano_publicacao,
    'DOI': DOI,
    'tipo_publicacao': tipo_publicacao,
    'resumo': resumo,
    'link_deacesso': link_deacesso
}

df = pd.DataFrame([dados])
df.head()

,titulo,autor,ano_publicacao,DOI,tipo_publicacao,resumo,link_deacesso
0,Primary Care: Its Pokemon Moment,Bryan Becker,Epub 2024 Mar 29.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...,https://linkinghub.elsevier.com/retrieve/pii/S...

## Exercício 2: Automatizar o processo anterior para todos os links da lista
Extrair as informações abaixo de cada um dos links obtidos

- Título
- Autores
- Ano
- DOI
- Tipo de publicação
- Resumo
- Link

### Armazene todas as informações em um DataFrame

#### 1) Criar tabela para armazenar dados

In [60]:
dados = {
    'titulo': titulo,
    'autor': autor,
    'ano_publicacao': ano_publicacao,
    'DOI': DOI,
    'tipo_publicacao': tipo_publicacao,
    'resumo': resumo,
    'link_deacesso': link_deacesso
}

df = pd.DataFrame([dados])
df.head()

,titulo,autor,ano_publicacao,DOI,tipo_publicacao,resumo,link_deacesso
0,Primary Care: Its Pokemon Moment,Bryan Becker,Epub 2024 Mar 29.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...,https://linkinghub.elsevier.com/retrieve/pii/S...

#### 2) Obter dados dos links e armazenar na tabela

#### 3) Visualizar tabela

#### 4) Exportar DataFrame para Excel